# Generated by Django 4.0.5 on 2022-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='log',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
