# Generated by Django 4.0.1 on 2022-07-13 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploadfiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadfiles', '0002_document_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFileHash',
            field=models.FileField(blank=True, null=True, upload_to=uploadfiles.models.Document.hash_directory_path),
        ),
        migrations.CreateModel(
            name='bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=200)),
                ('done', models.IntegerField(default=0)),
                ('User', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
