# Generated by Django 4.0.1 on 2022-07-14 00:30

from django.db import migrations, models
import django.db.models.deletion
import uploadfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0003_alter_document_uploadedfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfStartProcess', models.DateTimeField(null=True)),
                ('dateTimeOfEndProcess', models.DateTimeField(null=True)),
                ('folder', models.CharField(max_length=200, null=True)),
                ('hashName', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=uploadfiles.models.files.get_hash)),
                ('fileExtension', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('bulletin', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadfiles.bulletin')),
                ('parent', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploadfiles.files')),
            ],
        ),
    ]
